name: CI Pipeline - Flask DevSecOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Bandit (Python security scan)
      run: |
        pip install bandit
        bandit -r flaskr

    - name: Build Docker image
      run: docker build -t flask-app .

    - name: Run Trivy scan on Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: flask-app
        format: table
        severity: CRITICAL,HIGH
    - name: Echo GitHub Secret (Securely)
      run: echo "Secret is ${{ secrets.FAKE_API_KEY }}"

